### ISSUE TITLE
wtf8_is_initial_byte() is wrong

### ISSUE THREAD

**Issue by akofer** [scoopr/wtf8#1]
as utf8 standard (see RFC3629), the correct one should be as below:

static inline int wtf8_is_initial_byte(char byte) {
	return (byte & 0x80) == 0 
  || (byte & 0b11100000) == 0b11000000
  || (byte & 0b11110000) == 0b11100000
  || (byte & 0b11111000) == 0b11110000;
}

**Comment by scoopr** [comment]
Oh I see, the bytes 0xf8 through 0xff were seen as valid initial bytes, when they are not. Good catch, thank you!
